import { Hospital, Ambulance, Bed, User, Emergency, Zone } from '../types';

export const BANGALORE_ZONES: Zone[] = [
  { id: 'whitefield', name: 'Whitefield IT Corridor', center_lat: 12.9698, center_lng: 77.7499 },
  { id: 'electronic_city', name: 'Electronic City Tech Hub', center_lat: 12.8452, center_lng: 77.6602 },
  { id: 'hebbal', name: 'Hebbal Flyover & North Corridor', center_lat: 13.0358, center_lng: 77.5970 },
  { id: 'koramangala', name: 'Koramangala Commercial Zone', center_lat: 12.9352, center_lng: 77.6245 },
  { id: 'jayanagar', name: 'Jayanagar & South Suburbs', center_lat: 12.9250, center_lng: 77.5938 },
  { id: 'yeshwanthpur', name: 'Yeshwanthpur Industrial/Transit', center_lat: 13.0285, center_lng: 77.5455 },
  { id: 'central_majestic', name: 'Central & Majestic EOC', center_lat: 12.9767, center_lng: 77.5713 },
  { id: 'kr_puram', name: 'KR Puram Junction & East Belt', center_lat: 13.0075, center_lng: 77.6959 },
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'h1',
    name: 'Victoria Hospital (BMCRI)',
    address: 'Fort Road, Near City Market, Kalasipalyam, Bengaluru',
    lat: 12.9634,
    lng: 77.5753,
    contact: '+91 80 2670 1150',
    contact_number: '+91 80 2670 1150',
    specialties: ['Trauma', 'Burn', 'ICU', 'General Emergency'],
    total_capacity: 60,
    availableBedsCount: 6,
    zone_id: 'central_majestic',
  },
  {
    id: 'h2',
    name: 'Bowring & Lady Curzon Hospital',
    address: 'Lady Curzon Rd, Shivaji Nagar, Bengaluru',
    lat: 12.9835,
    lng: 77.6015,
    contact: '+91 80 2559 1325',
    contact_number: '+91 80 2559 1325',
    specialties: ['General Emergency', 'Maternity', 'ICU'],
    total_capacity: 55,
    availableBedsCount: 5,
    zone_id: 'central_majestic',
  },
  {
    id: 'h3',
    name: 'NIMHANS Neuro & Trauma Center',
    address: 'Hosur Road, Lakkasandra, Bengaluru',
    lat: 12.9392,
    lng: 77.5959,
    contact: '+91 80 2699 5000',
    contact_number: '+91 80 2699 5000',
    specialties: ['Neurology', 'Stroke', 'Trauma', 'ICU'],
    total_capacity: 80,
    availableBedsCount: 7,
    zone_id: 'jayanagar',
  },
  {
    id: 'h4',
    name: 'St. Johns Medical College Hospital',
    address: 'Sarjapur Main Rd, John Nagar, Koramangala, Bengaluru',
    lat: 12.9304,
    lng: 77.6200,
    contact: '+91 80 2206 5000',
    contact_number: '+91 80 2206 5000',
    specialties: ['Trauma', 'Cardiac', 'ICU', 'General Emergency'],
    total_capacity: 90,
    availableBedsCount: 8,
    zone_id: 'koramangala',
  },
  {
    id: 'h5',
    name: 'Manipal Hospital Old Airport Road',
    address: '98 HAL Old Airport Rd, Kodihalli, Bengaluru',
    lat: 12.9577,
    lng: 77.6475,
    contact: '+91 80 2502 4444',
    contact_number: '+91 80 2502 4444',
    specialties: ['Cardiac', 'Stroke', 'ICU', 'Trauma'],
    total_capacity: 75,
    availableBedsCount: 6,
    zone_id: 'koramangala',
  },
  {
    id: 'h6',
    name: 'Narayana Health City',
    address: '258/A, Bommasandra Industrial Area, Anekal, Bengaluru',
    lat: 12.8123,
    lng: 77.6895,
    contact: '+91 80 7122 2222',
    contact_number: '+91 80 7122 2222',
    specialties: ['Cardiac', 'Trauma', 'Burn', 'ICU'],
    total_capacity: 100,
    availableBedsCount: 12,
    zone_id: 'electronic_city',
  },
  {
    id: 'h7',
    name: 'Manipal Hospital Hebbal (Columbia Asia)',
    address: 'Bellary Rd, Near Hebbal Flyover, Bengaluru',
    lat: 13.0478,
    lng: 77.5926,
    contact: '+91 80 4179 1000',
    contact_number: '+91 80 4179 1000',
    specialties: ['Trauma', 'General Emergency', 'ICU'],
    total_capacity: 50,
    availableBedsCount: 4,
    zone_id: 'hebbal',
  },
  {
    id: 'h8',
    name: 'Sakra World Hospital',
    address: 'Devarabeesanahalli, Marathahalli ORR, Bengaluru',
    lat: 12.9284,
    lng: 77.6836,
    contact: '+91 80 4969 4969',
    contact_number: '+91 80 4969 4969',
    specialties: ['Trauma', 'Stroke', 'ICU', 'Cardiac'],
    total_capacity: 65,
    availableBedsCount: 5,
    zone_id: 'whitefield',
  },
  {
    id: 'h9',
    name: 'Fortis Hospital Bannerghatta Road',
    address: '154/9, Bannerghatta Main Rd, Opposite IIMB, Bengaluru',
    lat: 12.8943,
    lng: 77.5985,
    contact: '+91 80 6621 4444',
    contact_number: '+91 80 6621 4444',
    specialties: ['Cardiac', 'Trauma', 'ICU'],
    total_capacity: 60,
    availableBedsCount: 5,
    zone_id: 'jayanagar',
  },
  {
    id: 'h10',
    name: 'Apollo Hospitals Bannerghatta',
    address: '154/11, Bannerghatta Main Rd, Opposite IIMB, Bengaluru',
    lat: 12.8958,
    lng: 77.5988,
    contact: '+91 80 2630 4050',
    contact_number: '+91 80 2630 4050',
    specialties: ['Cardiac', 'Maternity', 'ICU', 'Burn'],
    total_capacity: 60,
    availableBedsCount: 6,
    zone_id: 'jayanagar',
  },
];

export const INITIAL_BEDS: Bed[] = [
  // Victoria
  { id: 'b101', hospital_id: 'h1', bed_number: 'VIC-ICU-01', bed_type: 'ICU', status: 'available' },
  { id: 'b102', hospital_id: 'h1', bed_number: 'VIC-ICU-02', bed_type: 'ICU', status: 'occupied' },
  { id: 'b103', hospital_id: 'h1', bed_number: 'VIC-TRM-01', bed_type: 'Trauma', status: 'available' },
  { id: 'b104', hospital_id: 'h1', bed_number: 'VIC-GEN-01', bed_type: 'General', status: 'available' },
  // Bowring
  { id: 'b201', hospital_id: 'h2', bed_number: 'BOW-MAT-01', bed_type: 'Maternity', status: 'available' },
  { id: 'b202', hospital_id: 'h2', bed_number: 'BOW-GEN-01', bed_type: 'General', status: 'available' },
  // NIMHANS
  { id: 'b301', hospital_id: 'h3', bed_number: 'NIM-ICU-01', bed_type: 'ICU', status: 'available' },
  { id: 'b302', hospital_id: 'h3', bed_number: 'NIM-TRM-01', bed_type: 'Trauma', status: 'available' },
  // St. Johns
  { id: 'b401', hospital_id: 'h4', bed_number: 'STJ-ICU-01', bed_type: 'ICU', status: 'available' },
  { id: 'b402', hospital_id: 'h4', bed_number: 'STJ-TRM-01', bed_type: 'Trauma', status: 'available' },
  // Manipal Old Airport
  { id: 'b501', hospital_id: 'h5', bed_number: 'MNP-ICU-01', bed_type: 'ICU', status: 'available' },
  { id: 'b502', hospital_id: 'h5', bed_number: 'MNP-TRM-01', bed_type: 'Trauma', status: 'available' },
  // Narayana
  { id: 'b601', hospital_id: 'h6', bed_number: 'NH-ICU-01', bed_type: 'ICU', status: 'available' },
  { id: 'b602', hospital_id: 'h6', bed_number: 'NH-TRM-01', bed_type: 'Trauma', status: 'available' },
  // Sakra
  { id: 'b801', hospital_id: 'h8', bed_number: 'SKR-ICU-01', bed_type: 'ICU', status: 'available' },
  { id: 'b802', hospital_id: 'h8', bed_number: 'SKR-TRM-01', bed_type: 'Trauma', status: 'available' },
  // Fortis & Apollo
  { id: 'b901', hospital_id: 'h9', bed_number: 'FOR-ICU-01', bed_type: 'ICU', status: 'available' },
  { id: 'b1001', hospital_id: 'h10', bed_number: 'APO-ICU-01', bed_type: 'ICU', status: 'available' },
];

export const INITIAL_AMBULANCES: Ambulance[] = [
  {
    id: 'a1',
    driver_id: 'u2',
    driver_name: 'Suresh Kumar',
    driver_phone: '+91 98765 43211',
    vehicle_number: 'KA-01-EA-1008',
    current_lat: 12.9715,
    current_lng: 77.5735,
    heading: 45,
    status: 'idle',
    standby_zone_id: 'central_majestic',
    hospital_id: 'h1',
  },
  {
    id: 'a2',
    driver_id: 'u-drv-2',
    driver_name: 'Ramesh Gowda',
    driver_phone: '+91 98765 43222',
    vehicle_number: 'KA-05-EM-9090',
    current_lat: 12.9350,
    current_lng: 77.6210,
    heading: 120,
    status: 'idle',
    standby_zone_id: 'koramangala',
    hospital_id: 'h4',
  },
  {
    id: 'a3',
    driver_id: 'u-drv-3',
    driver_name: 'Venkatesh Prasad',
    driver_phone: '+91 98765 43233',
    vehicle_number: 'KA-03-EM-4040',
    current_lat: 12.9720,
    current_lng: 77.7450,
    heading: 270,
    status: 'idle',
    standby_zone_id: 'whitefield',
    hospital_id: 'h8',
  },
  {
    id: 'a4',
    driver_id: 'u-drv-4',
    driver_name: 'Mohammed Aslam',
    driver_phone: '+91 98765 43244',
    vehicle_number: 'KA-51-EM-3030',
    current_lat: 12.8480,
    current_lng: 77.6630,
    heading: 90,
    status: 'idle',
    standby_zone_id: 'electronic_city',
    hospital_id: 'h6',
  },
  {
    id: 'a5',
    driver_id: 'u-drv-5',
    driver_name: 'Manjunath B',
    driver_phone: '+91 98765 43255',
    vehicle_number: 'KA-04-EM-7070',
    current_lat: 13.0380,
    current_lng: 77.5990,
    heading: 180,
    status: 'idle',
    standby_zone_id: 'hebbal',
    hospital_id: 'h7',
  },
  {
    id: 'a6',
    driver_id: 'u-drv-6',
    driver_name: 'Prakash Reddy',
    driver_phone: '+91 98765 43266',
    vehicle_number: 'KA-05-EM-1122',
    current_lat: 12.9230,
    current_lng: 77.5910,
    heading: 30,
    status: 'idle',
    standby_zone_id: 'jayanagar',
    hospital_id: 'h3',
  },
  {
    id: 'a7',
    driver_id: 'u-drv-7',
    driver_name: 'Sunil Naidu',
    driver_phone: '+91 98765 43277',
    vehicle_number: 'KA-02-EM-5544',
    current_lat: 13.0290,
    current_lng: 77.5480,
    heading: 60,
    status: 'idle',
    standby_zone_id: 'yeshwanthpur',
  },
  {
    id: 'a8',
    driver_id: 'u-drv-8',
    driver_name: 'Ganesh Bhat',
    driver_phone: '+91 98765 43288',
    vehicle_number: 'KA-53-EM-8877',
    current_lat: 13.0100,
    current_lng: 77.6980,
    heading: 210,
    status: 'idle',
    standby_zone_id: 'kr_puram',
  },
  {
    id: 'a9',
    driver_id: 'u-drv-9',
    driver_name: 'Dharmendra Yadav',
    driver_phone: '+91 98765 43299',
    vehicle_number: 'KA-01-EM-9900',
    current_lat: 12.9560,
    current_lng: 77.6490,
    heading: 150,
    status: 'idle',
    standby_zone_id: 'koramangala',
  },
  {
    id: 'a10',
    driver_id: 'u-drv-10',
    driver_name: 'Shiva Kumar',
    driver_phone: '+91 98765 43200',
    vehicle_number: 'KA-03-EM-1234',
    current_lat: 12.9640,
    current_lng: 77.7520,
    heading: 310,
    status: 'idle',
    standby_zone_id: 'whitefield',
  },
];

export const DEMO_USERS: User[] = [
  {
    id: 'u1',
    name: 'Rahul Sharma (Patient)',
    phone: '+919876543210',
    email: 'patient.demo@ambunet.in',
    role: 'patient',
    medical_profile: {
      blood_group: 'O+',
      allergies: 'Penicillin',
      conditions: 'Asthma, Hypertension',
      emergency_contact: 'Priya Sharma (+91 9876543219)',
      age: 38,
    },
  },
  {
    id: 'u2',
    name: 'Suresh Kumar (Driver)',
    phone: '+919876543211',
    email: 'driver.demo@ambunet.in',
    role: 'driver',
  },
  {
    id: 'u3',
    name: 'Dr. Ananya Rao (Hospital Staff)',
    phone: '+919876543212',
    email: 'hospital.demo@ambunet.in',
    role: 'hospital_staff',
    hospital_id: 'h1',
  },
  {
    id: 'u4',
    name: 'Commander Vikram Singh (Admin)',
    phone: '+919876543213',
    email: 'admin.demo@ambunet.in',
    role: 'admin',
  },
];

export const INITIAL_EMERGENCIES: Emergency[] = [
  {
    id: 'e1',
    patient_id: 'u1',
    patient_name: 'Rahul Sharma',
    patient_phone: '+919876543210',
    patient_medical_profile: {
      blood_group: 'O+',
      allergies: 'Penicillin',
      conditions: 'Asthma',
    },
    emergency_type: 'cardiac',
    severity: 'P1',
    symptoms: { chestPain: true, unconscious: false },
    pickup_lat: 12.9360,
    pickup_lng: 77.6250,
    pickup_address: 'Koramangala 5th Block, Bengaluru, Karnataka',
    zone_id: 'koramangala',
    status: 'requested',
    predicted_eta_sec: 420,
    actual_response_sec: undefined,
    distance_km: 3.2,
    created_at: new Date(Date.now() - 3 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60000).toISOString(),
  },
];
